spring:
  datasource:
    username: pet_store  # Database username
    password: pet_store  # Database password
    url: jdbc:mysql://localhost:3306/pet_store  # JDBC connection URL for MySQL
    driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL JDBC driver class

  jpa:
    hibernate:
      ddl-auto: create  # Specifies Hibernate's database schema generation strategy.
                        # Options: 
                        # - `create` (Drops and creates the database schema at startup)
                        # - `update` (Modifies schema without dropping data)
                        # - `validate` (Checks schema without making changes)
                        # - `none` (Disables schema generation)
    show-sql: true  # Enables SQL query logging in the console for debugging

  sql:
    init:
      mode: always  # Determines when SQL initialization scripts should be run.
                    # Options:
                    # - `always` (Executes scripts at startup for all environments)
                    # - `never` (Does not run initialization scripts)
                    # - `embedded` (Runs scripts only for embedded databases like H2)
